stages:
    - solution_01_build
    - solution_01_test
    - solution_02_build
    - solution_02_build_view_dat
    - solution_02_build_view_stat
    - solution_03_build
    - solution_04_build
    - solution_04_test
    - solution_07_build
    - solution_08_build
    - code_manager_build
    - code_manager_test


solution_01_build_job:
    stage: solution_01_build
    image: registry.gitlab.com/gluttton/pslrk:base
    before_script:
        - BUILD_DIR=`pwd`/Solutions/01
        - cd ${BUILD_DIR}
    script:
        - make


solution_01_test_job:
    stage: solution_01_test
    image: registry.gitlab.com/gluttton/pslrk:base
    before_script:
        - BUILD_DIR=`pwd`/Solutions/01
        - cd ${BUILD_DIR}
    script:
        - make testing
        - ./lpslcd.test
        - gcovr --exclude 'test' -r .


solution_02_build_job:
    stage: solution_02_build
    image: registry.gitlab.com/gluttton/pslrk:base
    before_script:
        - BUILD_DIR=`pwd`/Solutions/02
        - cd ${BUILD_DIR}
    script:
        - make


solution_02_build_view_dat_job:
    stage: solution_02_build_view_dat
    image: registry.gitlab.com/gluttton/pslrk:base
    before_script:
        - BUILD_DIR=`pwd`/Solutions/02
        - cd ${BUILD_DIR}
    script:
        - gcc view.dat.c -Wall -Wextra -o view.dat


solution_02_build_view_stat_job:
    stage: solution_02_build_view_stat
    image: registry.gitlab.com/gluttton/pslrk:base
    before_script:
        - BUILD_DIR=`pwd`/Solutions/02
        - cd ${BUILD_DIR}
    script:
        - gcc view.stat.c -Wall -Wextra -o view.stat


solution_03_build_job:
    stage: solution_03_build
    image: registry.gitlab.com/gluttton/pslrk:base
    before_script:
        - BUILD_DIR=`pwd`/Solutions/03/build
        - mkdir -p ${BUILD_DIR}
        - cd ${BUILD_DIR}
        - cmake -DCMAKE_BUILD_TYPE=Debug ${BUILD_DIR}/..
    script:
        - make


solution_04_build_job:
    stage: solution_04_build
    image: registry.gitlab.com/gluttton/pslrk:base
    before_script:
        - BUILD_DIR=`pwd`/Solutions/04
        - cd ${BUILD_DIR}
    script:
        - make


solution_04_test_job:
    stage: solution_04_test
    image: registry.gitlab.com/gluttton/pslrk:base
    before_script:
        - BUILD_DIR=`pwd`/Solutions/04
        - cd ${BUILD_DIR}
    script:
        - make testing
        - ./lpslcd.test
        - gcovr --exclude 'test' -r .


solution_07_build_job:
    stage: solution_07_build
    image: registry.gitlab.com/gluttton/pslrk:base
    before_script:
        - BUILD_DIR=`pwd`/Solutions/07
        - cd ${BUILD_DIR}
    script:
        - make


solution_08_build_job:
    stage: solution_08_build
    image: registry.gitlab.com/gluttton/pslrk:base
    before_script:
        - BUILD_DIR=`pwd`/Solutions/08
        - cd ${BUILD_DIR}
    script:
        - make


code_manager_build_job:
    stage: code_manager_build
    image: registry.gitlab.com/gluttton/pslrk:qt5.12.7
    before_script:
        - BUILD_DIR=`pwd`/Tools/CodeManager/build
        - mkdir -p ${BUILD_DIR}
        - cd ${BUILD_DIR}
        - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_PREFIX_PATH=/opt/qt/5.12.7 ${BUILD_DIR}/..
    script:
        - make


code_manager_test_job:
    stage: code_manager_test
    image: registry.gitlab.com/gluttton/pslrk:qt5.12.7
    before_script:
        - BUILD_DIR=`pwd`/Tools/CodeManager/build
        - mkdir -p ${BUILD_DIR}
        - cd ${BUILD_DIR}
        - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_PREFIX_PATH=/opt/qt/5.12.7 ${BUILD_DIR}/..
    script:
        - make tests
        - ./Core/test/CodeManagerCoreTest
        - gcovr --exclude '.*test' -r ..

